jellyfin_image: "jellyfin/jellyfin"
jellyfin_version: "latest"
jellyfin_container_name: "jellyfin"

jellyfin_ports:
  - "8096:8096"

jellyfin_uid: "1000"
jellyfin_gid: "1000"
jellyfin_user: "{{ jellyfin_uid }}:{{ jellyfin_gid }}"

jellyfin_data_path: "/srv/docker/jellyfin"
jellyfin_config_path: "{{ jellyfin_data_path }}/config"
jellyfin_cache_path: "{{ jellyfin_data_path }}/cache"
jellyfin_media_path: "/data/media"

jellyfin_volumes:
  - "{{ jellyfin_config_path }}:/config"
  - "{{ jellyfin_cache_path }}:/cache"
  - "{{ jellyfin_media_path }}:/media"

jellyfin_devices:
  - "/dev/dri:/dev/dri"

jellyfin_restart_policy: "unless-stopped"

jellyfin_env:
  TZ: "{{ timezone }}"

jellyfin_networks:
  - name: traefik

jellyfin_labels:
  traefik.enable: "true"
  traefik.docker.network: "traefik"
  traefik.http.routers.jellyfin.rule: "{{ 'Host(`' + JELLYFIN_URL + '`)' }}"
