$ANSIBLE_VAULT;1.1;AES256
62643637663339323835366365306531633662376239643065376239333834353333613062616537
3732366266356366303730303362303035626630356463320a313361653766353532616164323838
63666432386233616138656663356436373234623435626231666334623139343165346330656431
3037383332316636320a333334623739633861633434333962666564616265633833396439646135
38393832623634376462313230616437623064333739663230326334383334393535313239666436
3435636536623562373034616465366338353961393666346532
